[package]
name = "tcp_messenger_rs"
version = "0.2.0"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10.1"
chrono = "0.4.43"
clap = { version = "4.5.59", features = ["derive"] }
crossterm = "0.29.0"
rand_chacha = "0.3.1"
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
